name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title format
      uses: amannn/action-semantic-pull-request@v5
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        validateSingleCommit: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  size-label:
    name: Add Size Label
    runs-on: ubuntu-latest
    steps:
    - name: Add size label
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/XS'
        xs_max_size: '10'
        s_label: 'size/S'
        s_max_size: '100'
        m_label: 'size/M'
        m_max_size: '500'
        l_label: 'size/L'
        l_max_size: '1000'
        xl_label: 'size/XL'
        fail_if_xl: false

  pr-description:
    name: Check PR Description
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR has description
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const hasDescription = pr.body && pr.body.trim().length > 50;
          
          if (!hasDescription) {
            core.setFailed('PR description is too short. Please provide a detailed description of your changes.');
          }

  auto-assign:
    name: Auto Assign
    runs-on: ubuntu-latest
    steps:
    - name: Auto assign PR to author
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          if (!pr.assignees || pr.assignees.length === 0) {
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [pr.user.login]
            });
          }